### ISSUE TITLE
Upgrade to modoboa-radicale 1.6.1 error on dependecies and breaks Calendars and Contacts

### ISSUE THREAD

**Issue by tomas-kucera** [modoboa/modoboa-radicale#100]
When upgrading the modoboa-radicale from 1.6.0 to 1.6.1 the following errors occur:

```
modoboa-postfix-autoreply 1.7.0 requires django-filter==21.1, but you have django-filter 22.1 which is incompatible.
modoboa-contacts 0.9.0 requires caldav==0.9.0, but you have caldav 0.11.0 which is incompatible.
modoboa-contacts 0.9.0 requires django-filter==21.1, but you have django-filter 22.1 which is incompatible.
modoboa-contacts 0.9.0 requires django-webpack-loader==0.7.0, but you have django-webpack-loader 1.8.0 which is incompatible.
```

There is an issue with modoboa-contacts package dependencies.

As a result the Calendars and Contacts are broken - returning internal server error - 500.

FIX: revert back to 1.6.0 - `python -m pip install modoboa-radicale==1.6.0`

**Comment by tonioo** [comment]
We released new versions of contacts and autoreply plugins so it should work without warning now.
