### ISSUE TITLE
Calendar returns Sorry An internal error occured (Clean fresh Ubuntu setup)

### ISSUE THREAD

**Issue by rebelstartupper** [modoboa/modoboa-radicale#134]
# Impacted versions

- OS Type: Clean fresh Ubuntu
- OS Version: 22.04.1
- Database Type: Postgres
- Database version: PostgreSQL 14.10
- Modoboa: 2.2.4
- installer used: Yes
- Webserver: nginx/1.18.0
- python --version: Python 3.10.12

# Steps to reproduce

- Do a default install of Modoboa on ubuntu-22-04. (used the following guide: https://www.linuxbabe.com/mail-server/email-server-ubuntu-22-04-modoboa)
- Set up a first mail domain
- Set up a first user on the domain
- Logged into the user account, from mail.DOMAIN.com/webmail/
- Tried to access https://mail.domain.com/calendars/

# Current behaviour
Sorry
An internal error has occured.

# Expected behavior
Open calendar module

# Screenshot link
<img width="312" alt="305675619-99983812-055c-4c39-b53e-9ac9c6abb151" src="https://github.com/modoboa/modoboa-radicale/assets/63252498/383e64c8-820f-46ce-ad88-92eabc24d7b7">

When I went to /var/log/uwsgi/app/modoboa_instance.log. I found in the log the following:

mail.DOMAIN.com [pid: 1298|app: 1|req: 216/412] xxx.xxx.xxx.xxx () {64 vars in 1312 bytes} [Sun Feb 18 01:02:34 2024] GET /contacts/ => generated 5449 bytes in 86 msecs (HTTP/2.0 200) 6 headers in 307 bytes (1 switches on core 0)
mail.DOMAIN.com [pid: 1298|app: 1|req: 217/413] xxx.xxx.xxx.xxx () {60 vars in 1114 bytes} [Sun Feb 18 01:02:34 2024] GET /jsi18n/ => generated 3343 bytes in 39 msecs (HTTP/2.0 200) 5 headers in 171 bytes (1 switches on core 0)
mail.DOMAIN.com [pid: 1298|app: 1|req: 218/414] xxx.xxx.xxx.xxx () {64 vars in 1249 bytes} [Sun Feb 18 01:02:34 2024] GET /api/v1/contacts/ => generated 2 bytes in 52 msecs (HTTP/2.0 200) 6 headers in 193 bytes (1 switches on core 0)
mail.DOMAIN.com [pid: 1296|app: 1|req: 171/415] xxx.xxx.xxx.xxx () {64 vars in 1253 bytes} [Sun Feb 18 01:02:34 2024] GET /api/v1/categories/ => generated 2 bytes in 76 msecs (HTTP/2.0 200) 6 headers in 193 bytes (1 switches on core 0)
mail.DOMAIN.com [pid: 1298|app: 1|req: 219/416] xxx.xxx.xxx.xxx () {64 vars in 1275 bytes} [Sun Feb 18 01:02:34 2024] GET /api/v1/address-books/default/ => generated 95 bytes in 67 msecs (HTTP/2.0 200) 6 headers in 188 bytes (1 switches on core 0)
mail.DOMAIN.com [pid: 1296|app: 1|req: 172/417] xxx.xxx.xxx.xxx () {64 vars in 1311 bytes} [Sun Feb 18 01:02:35 2024] GET /webmail/ => generated 8883 bytes in 183 msecs (HTTP/2.0 200) 7 headers in 404 bytes (1 switches on core 0)
mail.DOMAIN.com [pid: 1298|app: 1|req: 220/418] xxx.xxx.xxx.xxx () {60 vars in 1113 bytes} [Sun Feb 18 01:02:36 2024] GET /jsi18n/ => generated 3343 bytes in 47 msecs (HTTP/2.0 200) 5 headers in 171 bytes (1 switches on core 0)
mail.DOMAIN.com [pid: 1296|app: 1|req: 173/419] xxx.xxx.xxx.xxx () {62 vars in 1294 bytes} [Sun Feb 18 01:02:37 2024] GET /webmail/?action=listmailbox&reset_page=true&=1708214554611 => generated 3883 bytes in 103 msecs (HTTP/2.0 200) 6 headers in 252 bytes (1 switches on core 0)
mail.DOMAIN.com [pid: 1296|app: 1|req: 174/420] xxx.xxx.xxx.xxx () {64 vars in 1314 bytes} [Sun Feb 18 01:02:37 2024] GET /calendars/ => generated 870 bytes in 137 msecs (HTTP/2.0 500) 5 headers in 181 bytes (1 switches on core 0)
mail.DOMAIN.com [pid: 1296|app: 1|req: 175/421] xxx.xxx.xxx.xxx () {60 vars in 1115 bytes} [Sun Feb 18 01:02:37 2024] GET /jsi18n/ => generated 3343 bytes in 61 msecs (HTTP/2.0 200) 5 headers in 171 bytes (1 switches on core 0)
mail.DOMAIN.com [pid: 1298|app: 1|req: 221/422] xxx.xxx.xxx.xxx () {62 vars in 1262 bytes} [Sun Feb 18 01:02:39 2024] GET /webmail/?action=listmailbox&=1708214557403 => generated 3883 bytes in 79 msecs (HTTP/2.0 200) 6 headers in 252 bytes (1 switches on core 0)
mail.DOMAIN.com [pid: 1296|app: 1|req: 176/423] xxx.xxx.xxx.xxx () {64 vars in 1312 bytes} [Sun Feb 18 01:02:40 2024] GET /contacts/ => generated 5449 bytes in 119 msecs (HTTP/2.0 200) 6 headers in 307 bytes (1 switches on core 0)
mail.DOMAIN.com [pid: 1298|app: 1|req: 222/424] xxx.xxx.xxx.xxx () {60 vars in 1114 bytes} [Sun Feb 18 01:02:40 2024] GET /jsi18n/ => generated 3343 bytes in 38 msecs (HTTP/2.0 200) 5 headers in 171 bytes (1 switches on core 0)
mail.DOMAIN.com [pid: 1298|app: 1|req: 223/425] xxx.xxx.xxx.xxx () {64 vars in 1253 bytes} [Sun Feb 18 01:02:40 2024] GET /api/v1/categories/ => generated 2 bytes in 63 msecs (HTTP/2.0 200) 6 headers in 193 bytes (1 switches on core 0)
mail.DOMAIN.com [pid: 1296|app: 1|req: 177/426] xxx.xxx.xxx.xxx () {64 vars in 1249 bytes} [Sun Feb 18 01:02:40 2024] GET /api/v1/contacts/ => generated 2 bytes in 66 msecs (HTTP/2.0 200) 6 headers in 193 bytes (1 switches on core 0)
mail.DOMAIN.com [pid: 1298|app: 1|req: 224/427] xxx.xxx.xxx.xxx () {64 vars in 1275 bytes} [Sun Feb 18 01:02:40 2024] GET /api/v1/address-books/default/ => generated 95 bytes in 53 msecs (HTTP/2.0 200) 6 headers in 188 bytes (1 switches on core 0)

We can see, the /api/v1/contacts is queried. But for calendar, no API requests (something like /api/v1/user-calendars/ )

As a fix, I tried downgrading django-webpack-loader to version 0.7.0, both contacts and calendars gave error, I brought it to version 2.0.1

**Comment by xEkkhysis** [comment]
Same here on a clean debian installation. Logs will be provided if needed.

**Comment by rebelstartupper** [comment]
I've just tried deleting the server and reinstall everything. Everything worked perfectly except this calendar. It's really annoying. Please, please, please, anyone can help or suggest a solution?

**Comment by blackhold** [comment]
Hi, I have the same problem. I activated debug = True in /srv/modoboa/instance/instance/settings.py and restarted uwsgi with service uwsgi restart.

What happens is:

![image](https://github.com/modoboa/modoboa-radicale/assets/113706/c8c01faa-e5e6-4753-93e8-61fe57e01bb7)

During handling of the above exception ([Errno 2] No such file or directory: '/srv/modoboa/env/lib/python3.9/site-packages/modoboa_radicale/static/modoboa_radicale/webpack-stats.json'), another exception occurred:

**Comment by i404788** [comment]
Also ran into this, seems like the versions of `django-filter` and `caldav` in `modoboa-contacts' are conflicting with those required by `modoboa_radicale`. Running `pip3 install -U modoboa_radicale==1.7.1` with the [venv active](https://modoboa.readthedocs.io/en/latest/upgrade.html#extensions) fixed it.
