### ISSUE TITLE
Handle also contact list

### ISSUE THREAD

**Issue by Toniob** [modoboa/modoboa-radicale#6]
Currently, this extension can only add a calendar . But radicale is also a carddav server. The modoboa-radicale extension should be able to add a contact list. Both are seen as a collection in radicale but as the frontend is using "calendar", it is confusing.

I think the extension should add the .vcf suffix to the name if we create a contact list or .ics in the case of a calendar.

**Comment by msenebald** [comment]
yep that would be nice

**Comment by tonioo** [comment]
@Toniob I guess we can close this issue since it is addressed by a dedicated plugin now (https://github.com/modoboa/modoboa-contacts)?

**Comment by Toniob** [comment]
Your new extension seems fine, but from what I understand, it doesn't handle carddav. Radicale does. It's not the same use case so.

Maybe you can do as we've talked before, keep this issue opened, and wait for Radicale 2.0 ?

**Comment by tonioo** [comment]
Ok, let's do this. I don't know where I'll put the carddav support yet...

**Comment by dugite-code** [comment]
I'm using this as a current workaround:

1. Create a calendar as normal

2. Go to your collection. For example a user calendar: /etc/radical/collections/domain.com/user/username/

3. edit `yourcalendar.prop` and change `{"tag": "VCALENDAR"}` to `{"tag": "VADDRESSBOOK"}`

Now you can connect to it with say the sogo connector on thunderbird and it will work (been using it for the past 4 months now).

Just be warned if you modify an existing calendar you will see some odd behaviors and will need to delete the `yourcalendar` file itself.

**Comment by tonioo** [comment]
Contacts and CardDAV synchronization are managed by the modoboa-contacts plugin.
