### ISSUE TITLE
Radicale rights file issue/error when trying to enable Carddav sync

### ISSUE THREAD

**Issue by extragreen** [modoboa/modoboa-radicale#69]
Every time I try to enable carddav sync:

![image](https://user-images.githubusercontent.com/11571540/103401096-c01be600-4b9b-11eb-9c15-e4c42c9cb28e.png)

It comes up with this error in /var/log/supervisor/radicale*.log:

`ERROR: An exception occurred during OPTIONS request on '/postmaster@DOMAIN.net/contacts': Error in section 'principal' of rights file '/etc/radicale/rights': 'user'`

My rights file looks like this:

![image](https://user-images.githubusercontent.com/11571540/103401216-1a1cab80-4b9c-11eb-9346-f9758382acf1.png)

Its missing something isn't it? Also could someone please let me know what the permissions for /etc/radicale/rights is meant to be?

I've tried doing `manage.py generate_rights --force` from my virtual env, the time on the rights file updates to the current time but nothing in the file changes. Is this normal?

I'm gonna try again after i've upgraded core modoboa but here's my versions in case it's not this:

![image](https://user-images.githubusercontent.com/11571540/103401411-c9598280-4b9c-11eb-9ac9-2dd9174cc339.png)

And my radicale version is definitely 2.1.12!

Thanks guys!

**Comment by tonioo** [comment]
@extragreen You need to upgrade Radicale to 3.x

**Comment by extragreen** [comment]
Happy new year @tonioo!
And thanks for the tip, updated to radicale 3.0.6 and works great now thanks!
