### ISSUE TITLE
Calendar URL for CALDAV?

### ISSUE THREAD

**Issue by lpossamai** [modoboa/modoboa-radicale#72]
I couldn't find this information in the documentation.

If I wanna use a CALDAV client on my android phone, which URL should I use? Using my email address or my mail server URL, I get a `Couldn't find CalDAV or CardDav service` error.

**Comment by tonioo** [comment]
From the web panel, Click on you calendar, a menu should appear. Select the fist entry (Information), it will open a popup where you can find the url you're looking for.

**Comment by lpossamai** [comment]
Worth updating the documentation with the above information.
