### ISSUE TITLE
Shared Calendars

### ISSUE THREAD

**Issue by malteneu** [modoboa/modoboa-radicale#75]
In the Calendars I am missing the Shared Calendar view. I cannot create any shared calendars even as Admin.

Current installed version is 1.5.1 and no Errors found so far in the Network Tab.

Regards,

Malte

![grafik](https://user-images.githubusercontent.com/71597734/127158616-5a84253f-6954-4d73-9fb4-82af68325f57.png)

**Comment by LexFuturorum** [comment]
https://you.domain.tld/docs/api/#/default/createSharedCalendar i tried creating one there but I got code:500 if you find a menu tell me where you found im searching for days now. #PERFECTDESIGN
